services:

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "2019:2019"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${DOCKER_ROOT}/caddy/caddyfile/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_ROOT}/caddy/data:/data
      - ${DOCKER_ROOT}/caddy/config:/config
    networks:
      - media
    restart: unless-stopped


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_ROOT}/portainer:/data
    networks:
      - media
    restart: unless-stopped

networks:
  media:
    driver: bridge
    name: media 

volumes:
  caddy_data:
  caddy_config:
