services:

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "2019:2019"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${DOCKER_ROOT}/caddy/caddyfile/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_ROOT}/caddy/data:/data
      - ${DOCKER_ROOT}/caddy/config:/config
    networks:
      - media
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/sonarr:/config
      - ${MEDIA_ROOT}:/Media
    networks:
      - media
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/radarr:/config
      - ${MEDIA_ROOT}:/Media
    networks:
      - media
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/prowlarr:/config
    networks:
      - media
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    ports:
      - 5055:5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/seerr:/app/config
      - ${MEDIA_ROOT}:/Media
    networks:
      - media
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
        - NET_ADMIN
    devices:
        - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - BLOCK_MALICIOUS=off
      - OPENVPN_PROTOCOL=${OPENVPN_PROTOCOL}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CIPHERS=${OPENVPN_CIPHERS}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
      - TZ=${TZ}
      - UPDATE_PERIOD=24h
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    ports:
        - "8080:8080"
    volumes:
      - ${DOCKER_ROOT}/gluetun:/gluetun
    networks:
      - media
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    volumes:
      - ${DOCKER_ROOT}/qbittorrent/data:/qbittorrent/data
      - ${DOCKER_ROOT}/qbittorrent/config:/config
      - ${MEDIA_ROOT}:/Media
      - ${DOCKER_ROOT}/qbittorrent/torrents:/torrents
      - ${FARM_ROOT}:/Media/Downloads/farm
    depends_on:
        - gluetun
    restart: unless-stopped
  

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6.13.6
    container_name: cross-seed
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/cross-seed:/config
      - ${DOCKER_ROOT}/qbittorrent/torrents:/torrents:ro
      - ${MEDIA_ROOT}:/media
    command: daemon
    networks:
      - media

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/jellyfin:/config
      - ${MEDIA_ROOT}:/Media
    networks:
      - media
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_ROOT}/portainer:/data
    networks:
      - media
    restart: unless-stopped

  joal:
    image: anthonyraymond/joal
    container_name: joal
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${DOCKER_ROOT}/joal:/data
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=${JOAL_PORT}", "--joal.ui.path.prefix=${JOAL_UI_PATH_PREFIX}", "--joal.ui.secret-token=${JOAL_UI_SECRET_TOKEN}"]
    depends_on:
      - gluetun

networks:
  media:
    driver: bridge
    name: media 

volumes:
  caddy_data:
  caddy_config: