services:
  
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/navidrome:/data
      - ${MEDIA_ROOT}/Music:/music:ro 
    networks:
      - media

  lidarr:
    image: ghcr.io/hotio/lidarr:pr-plugins
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/lidarr:/config
      - ${MEDIA_ROOT}/Music:/music
      - ${MEDIA_ROOT}/Downloads/music:/downloads
    networks:
      - media

networks:
  media:
    driver: bridge
    name: media 
